"""
Phase 1 Tool: Generate prefix migration SQL (non-destructive artifact).

Creates a SQL file with rename statements for:
- auth: sys_* -> asy_ (selected tables)
- mandant: sys_* -> msy_ (selected tables)

This script does not execute SQL.
"""

from __future__ import annotations

import argparse
from pathlib import Path

AUTH_RENAMES = {
    "sys_benutzer": "asy_benutzer",
    "sys_mandanten": "asy_mandanten",
    "sys_feld_aenderungshistorie": "asy_feld_aenderungshistorie",
}

MANDANT_RENAMES = {
    "sys_systemsteuerung": "msy_systemsteuerung",
    "sys_anwendungsdaten": "msy_anwendungsdaten",
    "sys_layout": "msy_layout",
    "sys_security": "msy_security",
    "sys_error_log": "msy_error_log",
    "sys_error_acknowledgements": "msy_error_acknowledgments",
    "sys_error_acknowledgments": "msy_error_acknowledgments",
    "sys_contr_dict_man": "msy_control_dict",
    "sys_contr_dict_man_audit": "msy_control_dict_audit",
    "sys_ext_table_man": "msy_ext_table",
    "sys_feld_aenderungshistorie": "msy_feld_aenderungshistorie",
}


def _render_section(title: str, renames: dict[str, str]) -> str:
    lines = [f"-- {title}"]
    for src, dst in renames.items():
        lines.append(f"DO $$")
        lines.append("BEGIN")
        lines.append(f"  IF to_regclass('public.{src}') IS NOT NULL AND to_regclass('public.{dst}') IS NULL THEN")
        lines.append(f"    EXECUTE 'ALTER TABLE public.{src} RENAME TO {dst}';")
        lines.append("  END IF;")
        lines.append("END $$;")
        lines.append("")
    return "\n".join(lines)


def _render_compat_views(title: str, renames: dict[str, str]) -> str:
    lines = [f"-- {title}"]
    for old_name, new_name in renames.items():
        lines.append("DO $$")
        lines.append("BEGIN")
        lines.append(f"  IF to_regclass('public.{new_name}') IS NOT NULL AND to_regclass('public.{old_name}') IS NULL THEN")
        lines.append(f"    EXECUTE 'CREATE VIEW public.{old_name} AS SELECT * FROM public.{new_name}';")
        lines.append("  END IF;")
        lines.append("END $$;")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SQL artifact for Phase 1 prefix migration")
    parser.add_argument(
        "--output",
        default="backend/reports/phase1_prefix_migration.sql",
        help="Target SQL file path",
    )
    args = parser.parse_args()

    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = Path.cwd() / output_path
    output_path.parent.mkdir(parents=True, exist_ok=True)

    content = [
        "-- PDVM Prefix Migration SQL Artifact",
        "-- Generated by backend/tools/phase1_generate_prefix_migration_sql.py",
        "-- IMPORTANT: Review before execution.",
        "",
        "BEGIN;",
        "",
        _render_section("AUTH DB RENAMES (sys_ -> asy_)", AUTH_RENAMES),
        _render_section("MANDANT DB RENAMES (sys_ -> msy_)", MANDANT_RENAMES),
        _render_compat_views("AUTH COMPAT VIEWS (old sys_* -> new asy_)", AUTH_RENAMES),
        _render_compat_views("MANDANT COMPAT VIEWS (old sys_* -> new msy_)", MANDANT_RENAMES),
        "COMMIT;",
        "",
    ]

    output_path.write_text("\n".join(content), encoding="utf-8")
    print(f"sql_artifact={output_path}")
    print(f"auth_rename_count={len(AUTH_RENAMES)}")
    print(f"mandant_rename_count={len(MANDANT_RENAMES)}")


if __name__ == "__main__":
    main()
